import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import HeroContent from '../components/HeroContent'
import HeroSlider from '../components/HeroImageSlider'
import About from '../components/About'
import Lineup from '../components/Lineup'
import Location from '../components/Location'
import GeneralInfo from '../components/GeneralInfo'
import RulesRegulations from '../components/RulesRegulations'
import MailingListSignup from '../components/NewsletterForm'

export default function Home() {
  return (
    <div className="franchise">
      <Head>
        <title>Camp Gooball</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/fonts/Franchise.ttf" as="font" type="font/ttf" crossOrigin=""/>
        <link rel="preload" href="/fonts/FranchiseFilled.ttf" as="font" type="font/ttf" crossOrigin=""/>
      </Head>
      <HeroSlider/>
      <div className={styles.container}>
        <HeroContent />
        <About />
        <Lineup />
        {/* <Location /> */}
        <GeneralInfo />
        <RulesRegulations />
        {/* <MailingListSignup /> */}
        <footer className={styles.footer}>
          <a
            href="https://jacksonkaufman.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Developed by Jackson Kaufman
          </a>
        </footer>
      </div>
    </div>
  )
}
