import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useEmblaCarousel from 'embla-carousel-react'
import Autoplay from 'embla-carousel-autoplay'
import React, { useEffect } from 'react'
import goofGroup from '../assets/images/GoofGroup1.jpg'
import groupOne from '../assets/images/group.jpg'
import groupThree from '../assets/images/TSgroup3.jpg'

export default function Home() {
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true, speed: 5 }, [Autoplay({delay: 7000})])
    useEffect(() => {
    if (emblaApi) {
      // Embla API is ready
    }
    }, [emblaApi])

  return (
    <>
      <div className="embla absolute w-full h-full z-10" ref={emblaRef}>
        <div className="embla__container w-full h-full">
          <div className="embla__slide h-full w-full">
            <Image
              className="slider-image"
              src={goofGroup}
              alt="Group Goof"
              layout="fill"
              objectFit="cover"
              objectPosition="center"
            />
          </div>
          <div className="embla__slide">
            <Image
              className="slider-image"
              src={groupOne}
              alt="Group Goof"
              layout="fill"
              objectFit="cover"
              objectPosition="center"
            />
          </div>
          <div className="embla__slide">
            <Image
              className="slider-image"
              src={groupThree}
              alt="Group Goof"
              layout="fill"
              objectFit="cover"
              objectPosition="center"
            />
          </div>
        </div>
      </div>
      <div className={styles.container}>
        <Head>
          <title>Camp Gooball</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Camp Goofball 2022!
          </h1>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}
