import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import HeroSlider from '../components/HeroSlider'
import HeroContent from '../components/HeroContent'
import MailingListSignup from '../components/NewsletterForm'

export default function Home() {
  return (
    <div className="franchise">
      <Head>
        <title>Camp Gooball</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/fonts/Franchise.ttf" as="font" type="font/ttf" crossOrigin=""/>
        <link rel="preload" href="/fonts/FranchiseFilled.ttf" as="font" type="font/ttf" crossOrigin=""/>
      </Head>
      <HeroSlider/>
      <div className={styles.container}>
        <HeroContent />
        <MailingListSignup />
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </div>
  )
}
